[package]
name = "findomain"
version = "2.1.5"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2018"
description = "The fastest and cross-platform subdomain enumerator, do not waste your time."
repository = "https://github.com/edu4rdshl/findomain"
license = "GPL-3.0-or-later"
keywords = ["discover-subdomains", "ct-logs", "search-subdomains", "enumerate-subdomains", "subdomain-scanner"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_derive = "1.0.118"
reqwest = { version = "0.11.0", features = ["blocking", "json", "gzip"] }
trust-dns-resolver = { version = "0.19.5", features = ["dns-over-rustls"] }
clap = { version = "2.33.3", features = ["yaml"] }
lazy_static = "1.4.0"
rand = "0.7.3"
postgres = "0.19.0"
failure = "0.1.8"
rayon = "1.5.0"
config = { version = "0.10.1", features = ["yaml", "json", "toml", "hjson", "ini"] }
headless_chrome = { git = "https://github.com/Edu4rdSHL/rust-headless-chrome" }

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.31", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.31", features = ["vendored"] }

[target.armv7-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.31", features = ["vendored"] }
