[package]
name = "findomain"
version = "8.1.1"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2021"
description = "The fastest and cross-platform subdomain enumerator, do not waste your time."
repository = "https://github.com/Findomain/Findomain"
license = "GPL-3.0-or-later"
keywords = ["discover-subdomains", "ct-logs", "search-subdomains", "enumerate-subdomains", "subdomain-scanner"]
readme = "README.md"
rust-version = "1.58"
resolver = "1"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
reqwest = { version = "0.11.10", features = ["blocking", "json", "gzip"] }
trust-dns-resolver = "0.20.4"
clap = { version = "2.33.4", features = ["yaml"] }
lazy_static = "1.4.0"
rand = "0.8.5"
postgres = "0.19.2"
rayon = "1.5.1"
config = { version = "0.11.0", features = ["yaml", "json", "toml", "hjson", "ini"] }
headless_chrome = { git = "https://github.com/Edu4rdSHL/rust-headless-chrome" }
addr = "0.15.3"
serde_json = "1.0.79"
rusolver = { git = "https://github.com/Edu4rdSHL/rusolver", rev = "88ee0f9b58ea89e6affb02f81c11b75983f1a497" }
fhc = { git = "https://github.com/Edu4rdSHL/fhc", rev = "728b8c078d5dcc6192fc8a607b9beeb66a7c1296" } 
tokio = "1.17.0"
crossbeam = "0.8.1"
futures = "0.3.21"
anyhow = "1.0.56"
postgres-native-tls = "0.5.0"
native-tls = "0.2.10"

# https://github.com/bluejekyll/trust-dns/pull/1632
[patch.crates-io]
trust-dns-resolver = { git = "https://github.com/Findomain/trust-dns", package = "trust-dns-resolver", branch = "custombranch" }

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.38", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.38", features = ["vendored"] }

[target.armv7-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.38", features = ["vendored"] }

[profile.release]
lto = 'thin'
codegen-units = 1
panic = 'abort'
incremental = false
opt-level = "s"
